#!/usr/bin/env zsh

_UTILNAME_cli_commands="
  UTILNAME help
  UTILNAME dev
  UTILNAME test
"

# display help
_UTILNAME_cli_help() {
cat <<EOF
ADD TITLE FOR UTILNAME AND DESCRIPTION

Syntax: UTILNAME <command> <<arg>...>

Commands:
...

EOF
}

UTILNAME() {
  local command=$1
  local param1=$2
  local param2=$3

  # open project {
  if [ -z "${command:-}" ]; then
    cd $_UTILNAME_cli_dir && vim
  # }
  # UTILNAME help {
  elif [ $command = 'help' ]; then
    _UTILNAME_cli_help
  # }
  # UTILNAME dev {
  if [ $command = 'dev' ]; then
    vim $_UTILNAME_cli_dir/index
  # }
  # UTILNAME test {
  elif [ $command = 'test' ]; then
    echo 'no tests'
  # }
  # display help when invalid command is provided {
  else
    _UTILNAME_cli_help
  fi
  # }
}

_UTILNAME_cli_complete() {
  local commands=($(echo $_UTILNAME_cli_commands | awk '/.+/ {print $2}'))
  local completions="$(echo $commands)"
  completions="$completions$(echo 'ADDITIONAL_AUTOCOMPLETE_HERE')"
  reply=( $(compgen -W ${completions[@]} -- $1) )
}

compctl -f -K _UTILNAME_cli_complete UTILNAME
